DROP TABLE IF EXISTS search;
DROP TABLE IF EXISTS analysis;

CREATE TABLE search (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    search_word TEXT UNIQUE NOT NULL
);

CREATE TABLE analysis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    search_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analysis_type TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (search_id) REFERENCES search (id)
)
